version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5410:5410"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  
    
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "gabriel@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "gabriel@123"
    ports:
      - "54321:80"
    depends_on:
      - postgres