version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER= DbUser
      - POSTGRES_PASSWORD= DbPassword
      - POSTGRES_DB= dbName
    ports:
      - "5410:5410"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  
    
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: PGADMIN_DEFAULT_PASSWORD
    ports:
      - "54321:80"
    depends_on:
      - postgres